/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

//import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import data.AudiovisualFile;
import data.BookFile;
import data.LoanFile;
import domain.Audiovisual;
import domain.Book;
import domain.Loan;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Pablo Castillo
 */
public class Return extends javax.swing.JInternalFrame {

    /**
     * Creates new form TablaNueva
     */
    //Attributes
    DefaultTableModel dtmModeloPrueba;
    JFrame frame;
    TableRowSorter trs;
    String id;
    Loan loan;

    public Return(JFrame frame) throws IOException, ClassNotFoundException {
        this.id = id;
        this.frame = frame;
        this.setClosable(true);
        this.setTitle("Return articles");
        initComponents();
        fillTable();
    }//constructor

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void penaltyBook(String name) {
        Date date = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        date = jDateChooser1.getDate();
        String fecha = dateFormat.format(date);
        try {
            LoanFile loanFile = new LoanFile();
            List<Loan> loanList = new ArrayList<Loan>();
            loanList = loanFile.returnLoanArray();
            for (int i = 0; i < loanList.size(); i++) {
                if (loanList.get(i).getBook() != null) {
                    if (loanList.get(i).getBook().getName().equals(name)) {
                        if (date.after(loanList.get(i).getEndDate())) {
                            JOptionPane.showMessageDialog(null, "You have a $25 fine for returning the book after the indicated date");
                        } else {
                            JOptionPane.showMessageDialog(null, "You have returned the book on time");
                        }
                    }
                }
            }
        } catch (IOException ex) {
        } catch (ClassNotFoundException ex) {
        }
    }

    public void penaltyAudiovisual(String code) {
        Date date = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        date = jDateChooser1.getDate();
        String fecha = dateFormat.format(date);
        try {
            LoanFile loanFile = new LoanFile();
            List<Loan> loanList = new ArrayList<Loan>();
            loanList = loanFile.returnLoanArray();
            for (int i = 0; i < loanList.size(); i++) {
                if (loanList.get(i).getAudio() != null) {
                    if (loanList.get(i).getAudio().getBrand().equals(code)) {
                        if (date.after(loanList.get(i).getEndDate())) {
                            JOptionPane.showMessageDialog(null, "You have a $25 fine for returning the material  after the indicated date");
                        } else {
                            JOptionPane.showMessageDialog(null, "You have returned the material on time");
                        }
                    }
                }
            }
        } catch (IOException ex) {
        } catch (ClassNotFoundException ex) {
        }
    }

    public void fillTable() throws IOException, ClassNotFoundException {
        BookFile bookFile = new BookFile();
        this.dtmModeloPrueba = new DefaultTableModel();
        this.dtmModeloPrueba.addColumn("Book");
        this.dtmModeloPrueba.addColumn("Audiovisual");
        this.dtmModeloPrueba.addColumn("Id");
        this.dtmModeloPrueba.addColumn("Start Date");
        this.dtmModeloPrueba.addColumn("End Datel");
        LoanFile loanFile = new LoanFile();
        List<Loan> bookList = loanFile.returnLoanArray();
        for (int i = 0; i < bookList.size(); i++) {
            this.dtmModeloPrueba.addRow(new Object[]{bookList.get(i).getBook(), bookList.get(i).getAudio(), bookList.get(i).getId(), bookList.get(i).getStartDate(), bookList.get(i).getEndDate()});
        }
        jTable1.setModel(dtmModeloPrueba);
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jLabel1.setText("Search by id");

        jLabel3.setText("Return date");

        jButton1.setText("Return loan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(305, 305, 305))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(jLabel3))
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int selection = jTable1.rowAtPoint(evt.getPoint());
        Book book = ((Book) jTable1.getValueAt(selection, 0));
        Audiovisual audiovisual = ((Audiovisual) jTable1.getValueAt(selection, 1));
        String id = (String) (jTable1.getValueAt(selection, 2));
        Date date1 = ((Date) jTable1.getValueAt(selection, 3));
        Date date2 = (Date) (jTable1.getValueAt(selection, 4));
        this.loan = new Loan(date1, date2, id, audiovisual, book);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        jTextField1.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                trs.setRowFilter(RowFilter.regexFilter("(?i)" + jTextField1.getText(), 2));
            }
        });
        trs = new TableRowSorter(dtmModeloPrueba);
        jTable1.setRowSorter(trs);
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased

    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LoanFile loanFile = new LoanFile();
        try {
            BookFile bookFile = new BookFile();
            AudiovisualFile audiovisual = new AudiovisualFile();
            if (this.loan.getBook() != null) {
                penaltyBook(this.loan.getBook().getName());
                bookFile.returnBook(this.loan.getBook().getCode());
                loanFile.deleteBook(this.loan.getBook().getCode());
            } else if (this.loan.getAudio() != null) {
                penaltyAudiovisual(this.loan.getAudio().getBrand());
                audiovisual.returnAudiovisual((this.loan.getAudio().getBrand()));
                loanFile.deleteAudiovisual(this.loan.getAudio().getBrand());

            }
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(Return.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Return.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
