/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import data.AudiovisualFile;
import domain.Audiovisual;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Pablo Castillo
 */
public class SearchAudioVisualByCode extends javax.swing.JInternalFrame {

    /**
     * Creates new form SearchAudioVisualByCode
     */
    JFrame ventana;
    Audiovisual audio;
    String carnet;
    public SearchAudioVisualByCode(JFrame frme,String carnet) {
        initComponents();
        ventana=frme;
        this.carnet=carnet;
       this.setClosable(true);
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("Audiovisual Code:");

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(208, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     AudiovisualFile archivo=new AudiovisualFile();
        try {
            boolean verificar=archivo.obtenerActorNombreBoolean2(Integer.parseInt(this.jTextField1.getText()));
             JOptionPane.showMessageDialog(null,verificar);
//               if(verificar==true){
//               archivo.actualizarCantidadDeAudiovi(Integer.parseInt(this.jTextField1.getText()));
               
//               }
//            JOptionPane.showMessageDialog(null,"el codigo no corresponde a algun material registrado");
            
//            List<String> personaList2 = new ArrayList<String>();
//            personaList2=archivo.search("a");
//            for(int i=0;i<personaList2.size();i++){
//            JOptionPane.showMessageDialog(null,personaList2.get(i));
//            }
            
               audio=archivo.obtenerActorNombre2(this.jTextField1.getText());
               
               JOptionPane.showMessageDialog(null, audio);
               
               
                 FechasPrestamoLibro calendario=new FechasPrestamoLibro(this.ventana,this.carnet,audio);
     this.ventana.add(calendario);
      calendario.setVisible(true);
      this.dispose();
               
            
        } catch (IOException ex) {
            Logger.getLogger(SearchAudioVisualByCode.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SearchAudioVisualByCode.class.getName()).log(Level.SEVERE, null, ex);
        }
     
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
