/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

//import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import data.AudiovisualFile;
import data.BookFile;
import data.LoanFile;
import domain.Audiovisual;
import domain.Book;
import domain.Loan;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Pablo Castillo
 */
public class TablaNuevaDevoluciones extends javax.swing.JInternalFrame {

    /**
     * Creates new form TablaNueva
     */
    DefaultTableModel dtmModeloPrueba;
    JFrame ventana;
    TableRowSorter trs;
    String carnet;
    Loan audio;

    public TablaNuevaDevoluciones(JFrame frame) throws IOException, ClassNotFoundException {
        this.carnet = carnet;
        ventana = frame;
        this.setClosable(true);
        initComponents();
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void multasLibros(String nombre){
        
        Date date = new Date();
         SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
         date = jDateChooser1.getDate();
         String fecha=dateFormat.format(date);
         
         
         
        try {
            LoanFile archivo=new LoanFile();
            
            List<Loan> personaList = new ArrayList<Loan>();
            personaList=archivo.arrays();
            for(int i=0; i<personaList.size();i++){
                if(personaList.get(i).getBook().getName().equals(nombre)){
                    if(date.after(personaList.get(i).getEndDate())){
                        JOptionPane.showMessageDialog(null, "Usted tiene una multa de $20 por devolver el libro después de la fecha indicada");
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Ha devuelto el libro a tiempo");
                    }
                   
                   
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(FechaDevolucion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FechaDevolucion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
 
 
 public void multasAudio(String nombre){
        
        Date date = new Date();
         SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
         date = jDateChooser1.getDate();
         String fecha=dateFormat.format(date);
         
         
         
        try {
            LoanFile archivo=new LoanFile();
            
            List<Loan> personaList = new ArrayList<Loan>();
            personaList=archivo.arrays();
            for(int i=0; i<personaList.size();i++){
                if(personaList.get(i).getAudio().getBrand().equals(nombre)){
                    if(date.after(personaList.get(i).getEndDate())){
                        JOptionPane.showMessageDialog(null, "Usted tiene una multa de $20 por devolver el libro después de la fecha indicada");
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Ha devuelto el libro a tiempo");
                    }
                   
                   
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(FechaDevolucion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FechaDevolucion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void llenarTabla() throws IOException, ClassNotFoundException {

        
//       LoanFile  archivo = new LoanFile();

        BookFile archivo = new BookFile();

        this.dtmModeloPrueba = new DefaultTableModel();
        this.dtmModeloPrueba.addColumn("libro");
        this.dtmModeloPrueba.addColumn("audiovisual");
        this.dtmModeloPrueba.addColumn("Carnet");
        this.dtmModeloPrueba.addColumn("Fecha Inicio");
        this.dtmModeloPrueba.addColumn("Fecha Final");

        //this.dtmModeloPrueba.addColumn("Availables");

        LoanFile archivoLibros = new LoanFile();
        List<Loan> listaLibros = archivoLibros.arrays();
        for (int i = 0; i < listaLibros.size(); i++) {
            this.dtmModeloPrueba.addRow(new Object[]{listaLibros.get(i).getBook(),listaLibros.get(i).getAudio(),listaLibros.get(i).getId(),listaLibros.get(i).getStartDate(),listaLibros.get(i).getEndDate()});
        }
        jTable1.setModel(dtmModeloPrueba);
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jLabel1.setText("Busqueda por nombre");

        jLabel3.setText("Fecha inicio del prestamo");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(305, 305, 305))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1))
                                .addGap(43, 43, 43))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(32, 32, 32)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

      
        int selection = jTable1.rowAtPoint(evt.getPoint());
        // JOptionPane.showMessageDialog(null,jTable1.getValueAt(selection,0));
       Book book = ((Book) jTable1.getValueAt(selection, 0));
        Audiovisual audio = ((Audiovisual) jTable1.getValueAt(selection, 1));
        String carnet = (String) (jTable1.getValueAt(selection, 2));
        Date date1 = ((Date) jTable1.getValueAt(selection, 3));
        Date date2 = (Date) (jTable1.getValueAt(selection, 4));
        

        // (String type, String brand, int amount, int available, int code,int madeYear)
        this.audio=new Loan(date1, date2, carnet, audio, book) ;

    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        jTextField1.addKeyListener(new KeyAdapter() {

            @Override
            public void keyReleased(KeyEvent e) {
                trs.setRowFilter(RowFilter.regexFilter("(?i)" + jTextField1.getText(), 2));

            }

        });
        trs = new TableRowSorter(dtmModeloPrueba);
        jTable1.setRowSorter(trs);
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased

    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
LoanFile archivo=new LoanFile();
              
           try{     
                BookFile libros=new BookFile();
                //Loan prestamo=archivo.obtenerLibro(jtfNombre.getText(),this.carnet,this.tipo);
                Loan prestamo = new Loan();
                JOptionPane.showMessageDialog(null,prestamo);
                
                if(audio.getBook()!=null){
                    multasLibros(audio.getBook().getName());
                libros.updateQuantityIncreasing(audio.getBook().getCode());
                
                    archivo.borrarLibro(audio.getBook().getCode());
                }else{
               
                AudiovisualFile audiovisual=new AudiovisualFile();
              //  Loan prestamo=archivo.obtenerLibro(jtfNombre.getText(),this.carnet,this.tipo);
               // JOptionPane.showMessageDialog(null,prestamo);
                multasAudio(audio.getAudio().getBrand());
                audiovisual.actualizarCantidadAumentando((audio.getAudio().getBrand()));
                
                archivo.borrarAudio(audio.getAudio().getBrand());
                
                }
            } catch (IOException ex) {
                Logger.getLogger(TablaNuevaDevoluciones.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(TablaNuevaDevoluciones.class.getName()).log(Level.SEVERE, null, ex);
            }
           
        
        
           
               
           
                
              
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
