/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import data.LoanFile;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Pablo Castillo
 */
public class ValidateReturn extends javax.swing.JInternalFrame {

    /**
     * Creates new form ValidateReturn
     */
    JFrame ventana;

    public ValidateReturn(JFrame frame) {
        ventana = frame;
        initComponents();
        this.setClosable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        jLabel1.setText("Write your id:");

        jButton1.setText("Give Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("AudioVisual");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Book");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addGap(40, 40, 40)
                        .addComponent(jRadioButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         if(jRadioButton2.isSelected()){
        try {
            LoanFile archivo = new LoanFile();
            boolean verifica = archivo.buscarCarnet(this.jTextField1.getText());
         
//            String tipo=
            if (verifica == true) {
                JOptionPane.showMessageDialog(null, "si existe  ");

                
                
                FechaDevolucion vericar = new FechaDevolucion(this.ventana,jTextField1.getText(),"libro");
                this.ventana.add(vericar);
                //  this.remove(jDesktopPane1);
                vericar.setVisible(true);
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(null, "no existe prestamo ");
                 JOptionPane.showMessageDialog(null, "si existe  ");

                
                
                FechaDevolucion vericar = new FechaDevolucion(this.ventana,jTextField1.getText(),"audio");
                this.ventana.add(vericar);
                //  this.remove(jDesktopPane1);
                vericar.setVisible(true);
                this.dispose();
                
            }

        } catch (IOException ex) {
            Logger.getLogger(ValidateReturn.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ValidateReturn.class.getName()).log(Level.SEVERE, null, ex);
        }
         }else  if(jRadioButton1.isSelected()){
         
             try {
                 LoanFile archivo = new LoanFile();
                 boolean verifica = archivo.buscarCarnet(this.jTextField1.getText());
                if(verifica=true){
                    FechaDevolucion internaPrestamos = new FechaDevolucion(this.ventana,jTextField1.getText(),"audio" );
                    this.ventana.add(internaPrestamos);
                    internaPrestamos.setVisible(true);
                    this.dispose();
                }
             } catch (IOException ex) {
                 Logger.getLogger(ValidateReturn.class.getName()).log(Level.SEVERE, null, ex);
             } catch (ClassNotFoundException ex) {
                 Logger.getLogger(ValidateReturn.class.getName()).log(Level.SEVERE, null, ex);
             }
         }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
