/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import data.StudentFile;
import domain.Student;
import java.beans.PropertyVetoException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Pablo Castillo
 */
public class VerificaStudent extends javax.swing.JInternalFrame {

    /**
     * Creates new form VerificaStudent
     */
    JFrame ventanaPrincipal;
    String carnet;

    public VerificaStudent(JFrame fra) {
        this.ventanaPrincipal = fra;

        initComponents();

        this.jRadioButton1.setEnabled(false);
        this.jRadioButton2.setEnabled(false);
        this.jButton2.setEnabled(false);
        this.jTextField2.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();

        jLabel1.setText("ingrese Carnet");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jRadioButton1.setText("libro");

        jRadioButton2.setText("AudioVisual");

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(47, 47, 47)
                                .addComponent(jRadioButton2)
                                .addGap(36, 36, 36)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(35, 35, 35)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jButton2))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            StudentFile archi = new StudentFile();

            boolean result = archi.buscarCarnet(this.jTextField1.getText());
            if (result == true) {
                JOptionPane.showMessageDialog(null, "entro");
                TipoPtrestamo pedir = new TipoPtrestamo(this.ventanaPrincipal, jTextField1.getText());
//                  this.ventanaPrincipal.add(pedir);
//                  pedir.setVisible(true);
//                  this.dispose();
                this.carnet=jTextField1.getText();
                Student student = archi.obtenerEstudiante(this.jTextField1.getText());
                jTextField2.setText("nombre" + " " + student.getName() + " " + "Apellido" + " " + student.getLastName());
//            jTextField2.setVisible(true);
                jTextField2.setEditable(false);
//            this.setFocusable(true);
//            this.ventanaPrincipal.repaint();
                this.jRadioButton1.setEnabled(true);
                this.jRadioButton2.setEnabled(true);
                this.jButton2.setEnabled(true);

            } else {
                JOptionPane.showMessageDialog(null, "no existe el usuario");
            }
        } catch (IOException ex) {
            Logger.getLogger(VerificaEstudiante.class.getName()).log(Level.SEVERE, null, ex);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(VerificaEstudiante.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
         if(jRadioButton2.isSelected()){
        
             try {
                 TablaNueva2 tabla=new TablaNueva2(this.ventanaPrincipal,this.carnet);
                 ventanaPrincipal.add(tabla);
                 tabla.setVisible(true);
                 this.dispose();
             } catch (IOException ex) {
                 Logger.getLogger(VerificaStudent.class.getName()).log(Level.SEVERE, null, ex);
             } catch (ClassNotFoundException ex) {
                 Logger.getLogger(VerificaStudent.class.getName()).log(Level.SEVERE, null, ex);
             }
         }else if(jRadioButton1.isSelected()){
             try {
                 //         JOptionPane.showMessageDialog(null, "ingreso");
//             MenuPrestamoLibro menuBusqueda=new MenuPrestamoLibro(ventanaPrincipal, carnet);
//             ventanaPrincipal.add(menuBusqueda);
//             menuBusqueda.setVisible(true);
//             this.dispose();
                 
                 TablaNueva tabla=new TablaNueva(this.ventanaPrincipal,this.carnet);
                 ventanaPrincipal.add(tabla);
                 tabla.setVisible(true);
                 this.dispose();
             } catch (IOException ex) {
                 Logger.getLogger(VerificaStudent.class.getName()).log(Level.SEVERE, null, ex);
             } catch (ClassNotFoundException ex) {
                 Logger.getLogger(VerificaStudent.class.getName()).log(Level.SEVERE, null, ex);
             }
             
         }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
